export default {
    assetManager: {
        addButton: "Rasm qo'shish",
        modalTitle: 'Rasmni tanlang',
        uploadTitle: 'Fayllarni yuklash uchun bu yerga tortib olib keling yoki bosing'
    },
    deviceManager: {
        device: 'Qurilma',
        devices: {
            desktop: 'Kompyuter',
            tablet: 'Tablet',
            mobileLandscape: 'Mobil formatda fon',
            mobilePortrait: 'Mobil formatda rasm'
        }
    },
    panels: {
        buttons: {
            titles: {
                preview: "Ko'rib chiqish",
                fullscreen: "To'liq ekran",
                'sw-visibility': "Komponentlarni ko'rsatish",
                'export-template': 'Kodni ko\'rsatish',
                'open-sm': 'Ochiq stil muharriri',
                'open-tm': 'Sozlamalar',
                'open-layers': 'Qatlamlar',
                'open-blocks': 'Bloklar'
            }
        }
    },
    selectorManager: {
        selected: 'Tanlangan',
        emptyState: '- STATUS -',
        label: 'Sinflar'
    },
    styleManager: {
        empty: 'Stilini tahrirlamoqchi bo\'lgan elementni tanlang',
        layer: 'Qatlam',
        sectors: {
            general: 'Umumiy',
            layout: 'Layout',
            typography: 'Tipografiya',
            decorations: 'Dekoratsiya',
            extra: 'Ekstra',
            flex: 'Flex',
            dimension: 'Hajmi'
        },
        properties: {
            float: 'Siljitish',
            display: 'Ko\'rsatish',
            position: 'Pozitsiya',
            top: 'Tepa',
            right: 'O\'ng',
            left: 'Chap',
            bottom: 'Past',
            width: 'Eni',
            height: 'Balandligi',
            'max-width': 'Maksimum eni',
            'max-height': 'Maksimum balandligi',
            margin: 'Margin',
            'margin-top': 'Tepadan margin',
            'margin-right': 'O\'ngdan margin',
            'margin-left': 'Chapdan margin',
            'margin-bottom': 'Pastdan margin',
            padding: 'Padding',
            'padding-top': 'Tepadan padding',
            'padding-left': 'Chapdan padding',
            'padding-right': 'O\'ngdan padding',
            'padding-bottom': 'Pastdan padding',
            'font-family': 'Font Tipi',
            'font-size': 'Font o\'lchami',
            'font-weight': 'Font Qalinligi',
            'letter-spacing': 'Harflar oralig\'i',
            color: 'Rang',
            'line-height': 'Satr balandligi',
            'text-align': 'Matnni tekislash',
            'text-shadow': 'Matn soyasi',
            'text-shadow-h': 'Matn soyasi - gorizontal',
            'text-shadow-v': 'Matn soyasi - vertikal',
            'text-shadow-blur': 'Matn soyasi xiralashuvi',
            'text-shadow-color': 'Matn soyasi rangi',
            'border-top-left': 'Yuqori chap burchak',
            'border-top-right': 'Yuqori o\'ng burchak',
            'border-bottom-left': 'Pastgi chap burchak',
            'border-bottom-right': 'Pastgi o\'ng burchak',
            'border-radius-top-left': 'Yuqori chap burchak radiusi',
            'border-radius-top-right': 'Yuqori o\'ng burchak radiusi',
            'border-radius-bottom-left': 'Pastgi chap burchak radiusi',
            'border-radius-bottom-right': 'Pastgi o\'ng burchak radiusi',
            'border-radius': 'Burchak radiusi',
            border: 'Chegara',
            'border-width': 'Chegara Qalinligi',
            'border-style': 'Chegara Stili',
            'border-color': 'Chegara Rangi',
            'box-shadow': 'Boks soyasi',
            'box-shadow-h': 'Boks soyasi - garizontal',
            'box-shadow-v': 'Boks soyasi - vertikal',
            'box-shadow-blur': 'Boks soyasi xiralashuvi',
            'box-shadow-spread': 'Boks soyasi tarqalishi',
            'box-shadow-color': 'Boks soyasi Rangi',
            'box-shadow-type': 'Boks soyasi Tipi',
            background: 'Fo\'n',
            'background-image': 'Fo\'n rasmi',
            'background-repeat': 'Fo\'n takrorlanishi',
            'background-position': 'Fo\'n joylashuvi',
            'background-attachment': 'Fo\'nning o\'rnatilganligi',
            'background-size': 'Fo\'n o\'lchami',
            transition: 'O\'tish',
            'transition-property': 'O\'tish xususiyati',
            'transition-duration': 'O\'tish davomiyligi',
            'transition-timing-function': 'O\'tish vaqtni hisoblash usuli',
            perspective: 'Perspektiva',
            transform: 'Transformatsiya',
            'transform-rotate-x': 'Gorizontal aylantirish(x)',
            'transform-rotate-y': 'Vertikal aylantirish(y)',
            'transform-rotate-z': 'Hajmli aylantirish(z)',
            'transform-scale-x': 'Vertikal nisbat(x)',
            'transform-scale-y': 'Gorizontal nisbat(y)',
            'transform-scale-z': 'Hajmli nisbat(z)',
            'flex-direction': 'Flex yo\'nalish',
            'flex-wrap': 'Flex qatlam',
            'justify-content': 'Kontentni tekislash',
            'align-items': 'Elementlarni tekislash',
            'align-content': 'Kontent joylashuvi',
            order: 'Qator',
            'flex-basis': 'Flex bazasi',
            'flex-grow': 'Flex o\'sishi',
            'flex-shrink': 'Flex qisqarishi',
            'align-self': 'O\'zini tekislash',
            'background-color': 'Orqa fon rangi'
        }
    },
    traitManager: {
        empty: 'Xususiyatlarini tahrirlamoqchi bo\'lgan narsani tanlang',
        label: 'Komponent xususiyatlari',
        traits: {
            labels: {},
            attributes: {},
            options: {}
        }
    }
};