dist: trusty
sudo: required
language: node_js
cache:
 - node_modules
node_js:
  - lts/*
jdk: oraclejdk8

#before_script:
#  - sudo safaridriver --enable
#  - defaults write com.apple.Safari IncludeDevelopMenu YES
#  - defaults write com.apple.Safari AllowRemoteAutomation 1
#  - defaults write com.apple.Safari LocalFileRestrictionsEnabled  0
#  - defaults write com.apple.Safari WebKit2ICECandidateFilteringEnabled 0
#  - defaults write com.apple.Safari WebKit2MockCaptureDevicesEnabled 1
#  - defaults write com.apple.Safari WebKit2MediaCaptureRequiresSecureConnection 0

branches:
  only:
    - gh-pages

script:
  - npm test

matrix:
  include:
  - name: "Chrome Stable"
    env: BROWSER=chrome
    addons:
      chrome: stable
  - name: "Firefox Stable"
    env: BROWSER=firefox
    addons:
      firefox: latest
  allow_failures:
  - name: "Chrome Beta"
    env: BROWSER=chrome
    addons:
      chrome: beta
  - name: "Firefox Beta"
    env: BROWSER=firefox
    addons:
      firefox: latest-beta
#  - name: "Safari"
#    env: BROWSER=safari
#  - name: "Firefox ESR"
#    env: BROWSER=firefox
#    addons:
#      firefox: latest-esr

notifications:
  email:
    recipients:
      forward-webrtc-github@webrtc.org
    on_success: change
    on_failure: always
