

<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/intercooler@1.2.3/dist/intercooler.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-mockjax@2.5.1/dist/jquery.mockjax.min.js"></script>


<div class="container">

    <div class="row">

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="demo">
                <!--
                This is the initial UI (which would normally be generated by the userDisplayTemplate below of course)
                Note that the button targets the outer div which encloses the entire contact UI because that's what we
                want to replace when the button is clicked.
                -->
                <div id="contact-div">
                    <div><strong>First Name</strong>: Joe</div>
                    <div><strong>Last Name</strong>: Smith</div>
                    <div><strong>Email</strong>: joesmith@example.com</div>
                    <button ic-target="#contact-div" ic-get-from="/one" class="btn btn-default">
                        Click To Edit
                    </button>
                </div>

                <script>

                    //========================================================================
                    // Mock Server-Side HTTP End Points
                    //========================================================================
                    $.mockjax({
                        url: "/one",
                        response: function (settings) {
                            var mockUser = dataStore.findUser("1");
                            this.responseText = userFormTemplate(mockUser);
                        }
                    });

                    $.mockjax({
                        url: "/one",
                        response: function (settings) {
                            var mockUser = dataStore.findUser("1");
                            var params = parseParams(settings.data);
                            if (params['_method'] == 'PUT') {
                                mockUser.firstName = params['firstName'];
                                mockUser.lastName = params['lastName'];
                                mockUser.email = params['email'];
                            }
                            this.responseText = userDisplayTemplate(mockUser);
                        }
                    });

                    //========================================================================
                    // Mock Server-Side Templates
                    //========================================================================
                    function userFormTemplate(mockUser) {
                        // Pretty simple bootstrap form, but note that the form uses an ic-put-to and the cancel button uses
                        // an ic-get-from rather than the usual HTML attributes
                        return '\
<form ic-put-to="/one" ic-target="#contact-div"> \
  <div class="form-group"> \
    <label>First Name</label> \
    <input type="text" class="form-control" name="firstName" value="' + mockUser.firstName + '"> \
  </div> \
  <div class="form-group"> \
    <label>Last Name</label> \
    <input type="text" class="form-control" name="lastName" value="' + mockUser.lastName + '"> \
  </div> \
  <div class="form-group"> \
    <label>Email address</label> \
    <input type="email" class="form-control" name="email" value="' + mockUser.email + '"> \
  </div> \
  <button class="btn btn-default">Submit</button> \
  <button ic-get-from="/one" ic-target="#contact-div" class="btn btn-danger">Cancel</button> \
</form>';
                    }

                    function userDisplayTemplate(mockUser) {
                        return '\
<div><strong>First Name</strong>: ' + mockUser.firstName + '</div> \
<div><strong>Last Name</strong>: ' + mockUser.lastName + '</div> \
<div><strong>Email</strong>: ' + mockUser.email + '</div> \
<button ic-target="#contact-div" ic-get-from="/one" class="btn btn-default"> \
  Click To Edit \
</button>';
                    }

                    //========================================================================
                    // Mock Data Store
                    //========================================================================
                    var dataStore = (function () {
                        var mockUser = {
                            "firstName": "Joe",
                            "lastName": "Smith",
                            "email": "joesmith@example.com"
                        };
                        return {
                            findUser: function (id) {
                                return mockUser
                            }
                        }
                    })()
                </script>
            </div>
            <div role="tabpanel" class="tab-pane" id="code">
                <pre id="src-pre"></pre>
            </div>
        </div>
    </div>
    <script>
        $("#src-pre").text($("#demo").html());
    </script>

</div>
</div>
